// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvQq4gLvqH9_PTxzyHJjSkcA-XaaKAis',
    appId: '1:501497831500:web:5caa525c5133331938d4e9',
    messagingSenderId: '501497831500',
    projectId: 'projetassad',
    authDomain: 'projetassad.firebaseapp.com',
    storageBucket: 'projetassad.firebasestorage.app',
    measurementId: 'G-EE1BNR2R51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdkw9aSWYYbe_cPl6MneyM9obu1rqx3tc',
    appId: '1:501497831500:android:c8d60ddba304292738d4e9',
    messagingSenderId: '501497831500',
    projectId: 'projetassad',
    storageBucket: 'projetassad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7wZo-QFiLNWNJO0Bs6W-x9UzTr5qBK4',
    appId: '1:501497831500:ios:dc9aba62403cf32338d4e9',
    messagingSenderId: '501497831500',
    projectId: 'projetassad',
    storageBucket: 'projetassad.firebasestorage.app',
    iosBundleId: 'com.example.tikitaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7wZo-QFiLNWNJO0Bs6W-x9UzTr5qBK4',
    appId: '1:501497831500:ios:dc9aba62403cf32338d4e9',
    messagingSenderId: '501497831500',
    projectId: 'projetassad',
    storageBucket: 'projetassad.firebasestorage.app',
    iosBundleId: 'com.example.tikitaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcvQq4gLvqH9_PTxzyHJjSkcA-XaaKAis',
    appId: '1:501497831500:web:a1d0e53f2ef55ad038d4e9',
    messagingSenderId: '501497831500',
    projectId: 'projetassad',
    authDomain: 'projetassad.firebaseapp.com',
    storageBucket: 'projetassad.firebasestorage.app',
    measurementId: 'G-3V1EN9SWB1',
  );
}
